# Generated by Django 3.1.3 on 2021-06-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=100)),
                ('total_order_amt', models.FloatField()),
                ('order_status', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
                ('order_place_date', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.TextField(max_length=400)),
                ('product_catg', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_pic', models.ImageField(upload_to='media')),
                ('product_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=14)),
                ('user_balance', models.FloatField()),
                ('profile_pic', models.ImageField(upload_to='media')),
                ('user_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product'),
        ),
    ]
