# Generated by Django 3.1.3 on 2021-06-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_creation_date',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_creation_date',
            field=models.TimeField(auto_now=True),
        ),
    ]
