# Generated by Django 3.1.3 on 2021-06-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20210611_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(default='', upload_to='Shop/Images'),
        ),
    ]
