# Generated by Django 3.1.3 on 2021-07-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
